FROM node:24.0.1-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG DIRECTUS_TOKEN
ARG DIRECTUS_URL

ENV DIRECTUS_TOKEN=$DIRECTUS_TOKEN
ENV DIRECTUS_URL=$DIRECTUS_URL

RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]
