name: Build Dev Website

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/tlis-web-dev:latest
        docker build . \
        --file Dockerfile \
        --tag $IMAGE_NAME \
        --build-arg NEXT_PUBLIC_DIRECTUS_URL=${{ secrets.DEV_DIRECTUS_URL }} 
        docker push $IMAGE_NAME
        
    - name: Deploy to production
      run: |
        curl -X GET "${{ secrets.DEPLOY_URL }}?uuid=${{ secrets.DEV_DEPLOY_ID }}&force=false" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_SECRET }}"